### PR TITLE
if comment filtering was requested, show it in title

### PR DESCRIPTION
**Pull request by Piskvor**

### CODE REVIEW

**Comment by iandees** [comment]
The comment isn't necessarily a pound sign, right? Also, if there's a comment in the title can we truncate it so the title's not huge and long?

**Comment by tmcw** [comment]
Thanks Jan!

**Comment by Piskvor** [comment]
@iandees: 1. True, haven't realized that it's only a OSMTM convention to #hashtag keywords.
2. Wouldn't tab size truncate the title anyway? It would only be visible in window title (which is hidden by default in Chrome and FF, IIRC) and as tab tooltip.

**Comment by iandees** [comment]
Yea, true!

**Pull request merged**
